version: 2
jobs:
  build:
    docker:
      - image: 'golang:latest'
    working_directory: /go/src/github.com/johanbrandhorst/protobuf
    steps:
      - checkout
      - run: go get -u github.com/gopherjs/gopherjs
      - run: make build
  dep:
    docker:
      - image: 'golang:latest'
    working_directory: /go/src/github.com/johanbrandhorst/protobuf
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: dep ensure -v
      - run: git diff --exit-code
  generate:
    docker:
      - image: 'golang:latest'
    working_directory: /go/src/github.com/johanbrandhorst/protobuf
    steps:
      - checkout
      - run:
          name: Install protoc
          environment:
            PROTOBUF_VERSION: "3.5.1"
          command: >
            apt-get update

            apt-get install -y unzip git wget python3

            rm -rf /var/lib/apt/lists/*

            wget
            https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-linux-x86_64.zip

            unzip protoc-${PROTOBUF_VERSION}-linux-x86_64.zip -d /usr/local

            rm protoc-${PROTOBUF_VERSION}-linux-x86_64.zip

            apt-get remove -y wget unzip

            apt-get autoremove -y
      - run:
          name: Install go dependencies
          command: >
            make install

            go get -u -v github.com/golang/protobuf/protoc-gen-go
            github.com/gopherjs/gopherjs
      - run:
          name: Regenerate
          command: |
            make regenerate
            git diff --exit-code
      - run:
          name: Generator tests
          command: make test
  tests:
    docker:
      - image: ypereirareis/docker-compose
    working_directory: /go/src/github.com/johanbrandhorst/protobuf
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Browser Integration Tests
          command: make integration
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - dep
      - generate
      - tests:
          requires:
            - generate
